import Head from 'next/head'
import { useState, useEffect } from 'react'

export default function Home() {
  type Properties = {
    review: {
      rich_text: { plain_text: string }[]
    }
    price: {
      rich_text: { plain_text: string }[]
    }
    name: {
      title: { text: { content: string } }[]
    }
  }
  const [products, setProducts] = useState<
    {
      id: string
      properties: Properties
    }[]
  >([])

  const [name, setName] = useState('')
  const [price, setPrice] = useState('')
  const [review, setReview] = useState('')
  useEffect(() => {
    fetch(`/api/get-items`)
      .then((res) => res.json())
      .then((data) => setProducts(data.items))
  }, [])

  const handleClick = () => {
    if (name.length === 0 || price.length === 0 || review.length === 0) {
      alert('모든 내용을 입력해 주세요.')
      return
    }
    fetch(`/api/add-item?name=${name}&price=${price}&review=${review}`)
      .then((res) => res.json())
      .then((data) => {
        alert(data.message)
        setName('')
        setPrice('')
        setReview('')
      })
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <input
          type="text"
          onChange={(e) => {
            setName(e.target.value)
          }}
          value={name}
          placeholder="name"
        />
        <br />
        <input
          type="text"
          onChange={(e) => {
            setPrice(e.target.value)
          }}
          value={price}
          placeholder="price"
        />
        <br />
        <input
          type="text"
          onChange={(e) => {
            setReview(e.target.value)
          }}
          value={review}
          placeholder="review"
        />
        <br />
        <button onClick={handleClick}>Add Jacket</button>

        <div>
          <p>Products</p>
          {products &&
            products.map((item, idx) => (
              <div key={idx}>
                {idx + 1}. 상품명:{' '}
                {JSON.stringify(item.properties.name.title[0].text.content)
                  .slice(1)
                  .slice(0, -1)}
                , 💵:{' '}
                {JSON.stringify(item.properties.price.rich_text[0].plain_text)
                  .slice(1)
                  .slice(0, -1)}
                원, 리뷰:{' '}
                {JSON.stringify(item.properties.review.rich_text[0].plain_text)
                  .slice(1)
                  .slice(0, -1)}
              </div>
            ))}
        </div>
      </main>
    </>
  )
}
